AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys New Relic Infrastructure into an existing Kubernetes Cluster (qs-1p7tp185f)
Parameters:
  HelmLambdaArn:
    Type: String
  KubeConfigPath:
    Type: String
  KubeConfigKmsContext:
    Type: String
    Default: "EKSQuickStart"
  KubeClusterName:
    Type: String
  NewRelicLicenseKey:
    Type: String
    NoEcho: true
Resources:
  KubeStateMetrics:
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      Chart: stable/kube-state-metrics
  NewRelic:
    DependsOn: KubeStateMetrics
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      Chart: stable/newrelic-infrastructure 
      # Custom values can optionally be specified
      Values:
        LicenseKey: !Ref NewRelicLicenseKey
        cluster: !Ref KubeClusterName
        apiserver.healthcheck.enabled: true
        imagePullPolicy: Always
